### ISSUE TITLE
Haunted Harvest succotash recipe isn't tagged properly

### ISSUE THREAD

**Issue by ZachsRoom** [Ninjdai1/letsdo-addon-compat#1]
Succotash's recipe is missing an ingredient in meadow's cooking pot and it's also not using ingredient tags either
![image](https://github.com/Ninjdai1/letsdo-addon-compat/assets/164839930/8e6a0933-7600-4260-81aa-b5fb889f7f90)
![image](https://github.com/Ninjdai1/letsdo-addon-compat/assets/164839930/978dcffb-1969-434d-af9a-9e88a54d55f6)
![image](https://github.com/Ninjdai1/letsdo-addon-compat/assets/164839930/b00c0bf9-cd81-41fd-8085-b7a83a212c5d)

**Comment by ZachsRoom** [comment]
![image](https://github.com/Ninjdai1/letsdo-addon-compat/assets/164839930/b7e51267-42cd-494b-b6b8-83b8a00b5bf8)
I used a datapack to change forge: tags to c: tags and it seems to be fixed

**Comment by Ninjdai1** [comment]
Could you send your modlist ?
I currently do not change tags, except for knives and cheese.
I'm working on fixing the fabric compat with c: tags, but that's mostly an issue with the mods that don't add it themselves, unless there's a way to automate it.

I don't know where the corn dough issue comes from, I'll look into it if I can reproduce it

**Comment by ZachsRoom** [comment]
Here's my mod list
	- abridged 1.1.1
	- adaptive-tooltips 1.3.0
	- advancementinfo 1.20-fabric0.83.0-1.4
	- advancementplaques 1.4.11
	- allthetrims 3.4.2
	- almostunified 1.20.1-0.9.2
	- amendments 1.20-1.1.12
	- animal_feeding_trough 1.0.3+1.20.1
	- antique-atlas 2.0.0+1.20
	- antique-fwaystones 1.2.0+1.19
	- anvilrestoration 2.2
	- appleskin 2.5.1+mc1.20
	- aquatictorches 1.0.1
	- arcanelanterns 8.0.0
	- architectury 9.2.14
	- armortip 1.0.0
	- artifacts 9.3.1
	- automaticdoors 4.6
	- autoslabs 1.1.3
	- autotag-convention 2.0.2+1.20
	- axesareweapons 1.7.3
	- azurelibarmor 2.0.3
	- badoptimizations 2.1.0
	- bakery 1.1.8
	- bakingdelight 0.2.1+1.20.1
	- balm-fabric 7.2.2
	- barteringstation 8.0.0
	- beachparty 1.1.4
	- bedbenefits 13.0.3
	- bee_info 1.1.2
	- beekeeperhut 2.0.0
	- bellsandwhistles 0.4.5
	- better_beacons 2.0.0
	   |-- mixinextras 0.3.5
	- better_climbing 3
	- betterclouds 1.3.16+1.20.1
	- bettercombat 1.8.4+1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	- betterdungeons 1.20-Fabric-4.0.3
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- bettermounthud 1.2.2
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterspawnercontrol 4.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- bettertrims 2.2.3
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bitsandchisels 2.7.3
	- bloomingnature 1.0.6
	- bookshelf 20.1.9
	- botanypots 13.0.26
	- botanypotstiers 6.0.1
	- botarium 2.3.3
	- bottleyourxp 3.3
	- bountiful 6.0.3+1.20.1
	- brewinandchewin fabric-2.3.1+1.20.1
	- bushierflowers 0.0.3-1.20.1
	- c2me 0.2.0+alpha.11.5
	- cakechomps 6.2.0+1.20.1
	- cakedelight 1.20.1-v3.0.2
	- cameraoverhaul 1.4.0-fabric-universal
	- candlelight 1.2.10
	- cardinal-components 5.2.2
	- carryon 2.1.2.7
	- cat_jam 1.2.1
	- catalogue 1.8.0
	- cavedust 1.4.1
	- cavespiderspawn 1.1
	- cerbons_api 1.1.0
	- chat_heads 0.10.32
	- chefsdelight 1.0.3-fabric-1.20.1
	- cherishedworlds 6.1.6+1.20.1
	- chickensshed 1.5.0+1.20.1
	- chunksfadein 1.0.5-1.20.1
	- cleardespawn 1.1.15
	- cloth-config 11.1.118
	- clumps 12.0.0.3
	- collective 7.40
	- companion 5.1.0
	- configured 2.2.3
	- conjuring 1.0.29+1.20
	- continuity 3.0.0-beta.4+1.20.1
	- controlling 12.0.2
	- copycats 1.20.1-1.2.6
	- coroutil 1.20.1-1.3.7
	- cosmetic-armor 1.6.0
	- couplings 1.9.5+1.20
	- cratedelight 1.4.4-1.20.1-fabric
	- crawl 0.12.0
	- create 0.5.1-f-build.1335+mc1.20.1
	- create_new_age 1.1.2
	- create_oxidized 0.1.1+1.20.1
	- create_structures 1.1.0
	- createaddition 1.2.3
	- createfood 1.0.3
	- createmetalwork 1.0.0
	- createoreexcavation 1.4.5
	- createutilities 0.3.0+1.20.1
	- creativecore 2.11.24
	- creeperoverhaul 3.0.2
	- ctov 3.4.2
	- culturalcreators 1.0.0
	- culturaldelights 0.14.12+1.20.1
	- damagenumbers 1.1.0-fabric
	- decorative_blocks 4.1.3
	- delightfulcreators 1.1.8
	- dismountentity 3.2
	- doapi 1.2.9
	- doggytalents 1.18.10
	- draggable_lists 1.0.1
	- dummmmmmy 1.20-1.8.14
	- dungeon_difficulty 2.0.6+1.20.1
	- dynamiccrosshair 7.4.4+1.20
	- dynamiccrosshaircompat 3.7.2+1.20.1
	- e4mc_minecraft 4.0.1
	- easiervillagertrading 1.20-fabric0.83.0-1.5.4
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- easyshulkerboxes 8.0.2
	- eatinganimationid 1.20+1.9.61
	- eldritch_mobs 1.15.1
	- elytra_trinket 1.0.3
	- ember_kiln 1.0.4
	- emi 1.1.4+1.20.1+fabric
	- emi_enchanting 0.1.0+1.20.1
	- emi_loot 0.6.5+1.20.1
	- emi_ores 0.4+1.20.1
	- emiffect 1.1.2+mc1.20.1
	- emitrades 1.2.1+mc1.20.1
	- enchdesc 17.0.14
	- endermanoverhaul 1.0.4
	- endportalrecipe 5.2
	- endrem 5.2.4
	- ends_delight 1.0.1
	- enhancedblockentities 0.9+1.20
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	- entityculling 1.6.2-mc1.20.1
	- equipmentcompare 1.3.8
	- evenbetterarcheology 2.0.0-beta.6
	- everycomp 1.20-2.6.39
	- expandeddelight 0.3.0.3
	- experienced_crops 1.20.1-1.1.0
	- explorations 1.20.1-1.5.2
	- explorify v1.3.0-mc1.20
	- extendedbonemeal 3.3
	- extendedgears 2.1.1-1.20.1-fabric
	- extra-mod-integrations 0.4.3+1.20.1
	- extraalchemy 1.10.0
	- fabric-api 0.92.0+1.20.1
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	- fabricloader 0.15.7
	- fallingleaves 1.15.5
	- farmersdelight 1.20.1-1.4.3
	- farmersknives 3.0.2
	- farmersrespite 2.3.4
	- ferritecore 6.0.1
	- festive_delight 1.0.0
	- fixedanvilrepaircost 3.3
	- flowerymooblooms 2.0.1
	- fog-looks-good-now 2.2.0+1.20.1
	- forgeconfigapiport 8.0.0
	- forgottenrecipes 1.2.0
	- framework 0.6.27
	- friendsandfoes 2.0.10
	- frightsdelight 1.20.1-1.0.1
	- fsit v1.5.1-1.20
	- fusion 1.1.1
	- fwaystones 3.3.2+mc1.20.1
	- geckolib 4.4.4
	- geodes 1.9
	- giantspawn 5.0
	- glassbreaker 1.4.0
	- go-fish 1.6.3+1.20.1
	- goblintraders 1.9.3
	- goldenhopper 1.4.1
	- guardvillagers 2.0.9-1.20.1
	- guiclock 4.4
	- guicompass 4.4
	- handcrafted 3.0.6
	- handoveryouritems 3.3
	- hauntedharvest 1.20-3.1.20
	- hauntfurnace 0.2-1.20.1
	- heater 1.2.0+1.20.1
	- held-item-info 1.5.0
	- herbalbrews 1.0.6
	- highlight 2.0.1
	- highlighter 1.1.9
	- hoetweaks 3.4
	- hopobettermineshaft 1.1.8
	- hopobetterruinedportal 1.3.7
	- hopobetterunderwaterruins 1.1.4
	- iceberg 1.1.18
	- illagerinvasion 8.0.4
	- immediatelyfast 1.2.11+1.20.4
	- immersive_aircraft 0.7.5+1.20.1
	- immersive_paintings 0.6.7+1.20.1
	- immersive_weathering 1.20.1-2.0.1
	- improvedsignediting 1.1
	- indium 1.0.30+mc1.20.4
	- inventoryhud 3.4.18
	- inventorymanagement 1.3.1
	- ironchests 5.0.2
	- item_obliterator 2.1.0
	- itemborders 1.2.2
	- jade 11.8.0
	- jadeaddons 5.2.3
	- java 17
	- jei 15.3.0.4
	- jepp 1.20-1.1.2
	- jmc 1.17.4
	- jumpoverfences 1.3.1
	- just_enough_beacons 1.2.0
	- justenoughbreeding 1.2.1
	- justenoughprofessions 3.0.1
	- kambrik 6.1.1+1.20.1
	- keepmysoiltilled 2.2
	- kiwi 11.5.5
	- labels 1.20-1.20.1
	- lambdynlights 2.3.2+1.20.1
	- lampcrafting 1.0.5
	- legendarytooltips 1.4.4
	- letsdoaddon-compat 1.3.0
	- letsdoaddon-structures 1.7.1
	- libipn 4.0.2
	- libz 1.0.3
	- lithium 0.11.2
	- lootbeams 1.0.3
	- lootr 0.7.30.77
	- luphieclutteredmod 2.1.0+1.20.1
	- magnumtorch 8.0.2
	- man_of_many_planes 0.0.3+1.20.1
	- maptooltip 3.0.0
	- mcda 5.0.1
	- mcdw 9.0.1
	- mcmddj 1.0.2
	- mcwbridges 2.1.0
	- mcwdoors 1.1.0
	- mcwfences 1.1.1
	- mcwfurnitures 3.2.2
	- mcwlights 1.0.6
	- mcwpaths 1.0.4
	- mcwroofs 2.3.0
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.1
	- meadow 1.3.7
	- menulogue 1.20.1-1.0.4
	- merchantmarkers 1.3.1
	- mes 1.3-1.20-fabric
	- minecraft 1.20.1
	- mns 1.0-1.20-fabric
	- modelfix 1.15
	- modernfix 5.15.0+mc1.20.1
	- monsters_in_the_closet 1.0.3+1.20
	- moonlight 1.20-2.11.9
	- mooshroomspawn 3.5
	- mooshroomtweaks 3.4
	- more_spawners 1.1.0
	- morebannerfeatures 1.2.0
	- moreculling 1.20.4-0.22.1
	- morediscs 1.20.1-33-fabric
	- moremobvariants 1.2.2
	- mousetweaks 2.25
	- mr_cheaper_maps 1.0
	- mr_ctov_chefsdelightcompat 2.0
	- mr_ctov_createstructures 1.0
	- mr_ctov_farmersdelightcompat 2.1
	- mr_ctov_friendsandfoescompat 2.0
	- mr_dungeons_andtaverns 3.0.3.f
	- mr_dungeons_andtavernsancientcityoverhaul 1
	- mr_dungeons_andtavernspillageroutpostrework 1.1
	- mr_dungeons_andtavernsstrongholdrework 1
	- mr_dungeons_andtavernsswamphutrework 1
	- mr_edf_remastered 4.3
	- mr_glowstone_itemframes 1.0
	- mru 0.4.0+1.20
	- multibeds 1.20.1-1.2
	- mvs 4.1.1-1.20-fabric
	- nameplate 1.1.4
	- naturalist 4.0.3
	- naturallychargedcreepers 3.4
	- necronomicon 1.4.2
	- nethersdelight 1.0.0
	- nethervinery 1.2.9
	- netherwardblock 1.20.1-6-fabric
	- nets 0.3.5.5
	- neves_capybaras mc1.20.1-1.0.0
	- niftycarts 3.0.1+1.20.1
	- nightlights 1.1
	- noanimaltemptdelay 1.1
	- nochatreports 1.20.1-v2.2.2
	- nofeathertrample 1.2
	- nohostilesaroundcampfire 5.9
	- noisium 1.0.2+mc1.20.x
	- notenoughanimations 1.7.1
	- numismatic-overhaul 0.2.14+1.20
	- nyfsspiders 2.1.1
	- obscure_api 16
	- oceansdelight fabric-1.0.2-1.20
	- openloader 19.0.3
	- optigui 2.1.7
	- overflowingbars 8.0.0
	- overweight_farming 1.20.1-2.0.3-fabric
	- overworldpiglins 1.4
	- owo 0.11.2+1.20
	- panorama_screens 1.0+fabric+mc1.20
	- paperbooks 3.2
	- passiveshield 3.4
	- patchouli 1.20.1-84-FABRIC
	- pathunderfencegates 1.4.0+mc1.20.x
	- pickupnotifier 8.0.0
	- player-animator 1.0.2-rc1+1.20
	- plushables 1.1.3
	- polymer-bundled 0.5.19+1.20.1
	- polymorph 0.49.3+1.20.1
	- presencefootsteps 1.9.2
	- prism 1.0.5
	- projectile_damage 3.2.2+1.20.1
	- puffish_skills 0.11.3
	- puzzleslib 8.1.18
	- quartzelv 2.2.6+1.20
	- radiantgear 2.1.0+1.20.1
	- railways 1.5.3+fabric-mc1.20.1
	- rain-grow 1.2
	- rainbegoneritual 3.2
	- rare-ice 0.6.0
	- rechiseled 1.1.5+b
	- rechiseledcreate 1.0.2
	- refurbished_furniture 1.0.0-beta.3
	- repurposed_structures 7.1.13+1.20.1-fabric
	- reputation 0.2.4+jade.1.20
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.24
	- respawninganimals 8.2.0
	- respawningshulkers 3.7
	- respitecreators 1.2.0
	- rsponge 1.0.0
	- sawmill 1.20-1.3.11
	- scaffoldingdropsnearby 3.2
	- screenshot_viewer 1.2.1-fabric-mc1.20
	- screenshotclipboard 1.0.9
	- seafoamsdyeableblocks 1.4.2
	- searchables 1.0.2
	- seasons 2.3+1.20
	- seasonsdelightcompat 1.0-1.3.9
	- seasonsextras 1.2-BETA+1.20
	- shakdel 1.0.0
	- shetiphiancore 1.20.1-1.2
	- shield_overhaul 1.0.3
	- showmeyourskin 1.8.0+1.20
	- skeletalremains 1.4.2
	- skeletonhorsespawn 3.8
	- skinlayers3d 1.6.2
	- sliceanddice 3.1.0
	- smallernetherportals 3.6
	- smallships 2.0.0-b1.1
	- smarterfarmers 1.20-1.8.2
	- smoothscrollingrefurbished 1.1.2
	- smwyg 1.1.1
	- snifferplus 0.2.0
	- snowrealmagic 10.4.2
	- snowundertrees 2.2.0+1.20.1
	- sodium 0.5.8+mc1.20.1
	- softerhaybales 3.2
	- sootychimneys 1.1.0
	- soulfired 3.2.1.0
	- sounds 0.6.0+1.20.1
	- sparsestructures 2.1.2
	- spawnanimations 1.9.4+mod
	- spell_engine 0.13.3+1.20.1
	- spell_power 0.9.19+1.20.1
	- spelunker 1.5.3-mc1.20
	- spelunkery 1.20.1-0.3.5
	- spiceoffabric 1.6.2+mc1.20.1
	- spidersproducewebs 3.3
	- spyglass-improvements 1.5+mc1.20+fabric
	- stonecutter-remastered 1.0.0beta2-1.20+Chipped
	- storagedelight 1.0.2
	- structure_pool_api 1.0+1.20.1
	- subterrestrial 2.2.0
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.7
	- suppsquared 1.20-1.1.14
	- surfacemushrooms 3.3
	- surveyor 0.1.0+1.20
	- tall-flower-pots 0.1.2
	- tawct 1.4.8+1.20-1.20.1
	- techsupportred 1.0.0
	- thaumon 2.2.0+1.20.1
	- things 0.3.3+1.20
	- threadtweak 1.20.2-0.1.1
	- tia 1.20-1.1
	- tiered 1.3.2
	- toastkiller 1.0
	- toolleveling 1.20.1-2.0.0
	- toolstats 16.0.8
	- towers 1.0.1
	- tradingpost 8.0.2
	- trashslot 15.1.0
	- travelersbackpack fabric-1.20.1-9.1.10
	- travelerz 1.0.1
	- treechop 0.19.0
	- trinkets 3.7.2
	- turkish_delight 1.0.0
	- ubesdelight 0.1.5b
	- universalbonemeal 8.0.1
	- universalenchants 8.0.0
	- unloadedactivity v0.5.0
	- vc_gliders 1.1.5
	- veinmining 1.4.0+1.20.1
	- villagernames 7.3
	- villagesandpillages 1.0.0
	- vinery 1.4.14
	- visuality 0.7.1+1.20
	- visualworkbench 8.0.0
	- vmp 0.2.0+beta.7.102
	- vt_downloader 2.0.8+1.20.1
	- watut 1.20.1-1.1.0
	- weakerspiderwebs 3.4
	- weaponmaster 3.0.5
	- wilderwild 2.3.3-Fabric+1.20.1
	- windchimes 1.2.4+1.20
	- wmitaf 3.2.0
	- wooltweaks 3.3
	- xercapaint fabric-1.20.1-1.0.0
	- yeetusexperimentus 2.3.0-build.4+mc1.20.1
	- yet_another_config_lib_v3 3.2.2+1.20
	- yigd 2.0.0-beta.11
	- yungsapi 1.20-Fabric-4.0.4
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3
	- yungsmenutweaks 1.20.1-Fabric-1.0.2
	- zombiehorsespawn 4.8

**Comment by Ninjdai1** [comment]
Can you try using the latest version (located at https://github.com/Ninjdai1/letsdo-addon-compat/releases) ?
I made separate forge/fabric versions, this should help with a lot of tag issues

**Comment by ZachsRoom** [comment]
I tried the latest version and the tags look good now :D
Also, I think recipes with only one ingredient is the cause. Normally without compat mod this recipe produce 2 bowl
![image](https://github.com/Ninjdai1/letsdo-addon-compat/assets/164839930/ffa9dca9-bd22-4cb8-a5c5-4d58e297729b)
![image](https://github.com/Ninjdai1/letsdo-addon-compat/assets/164839930/fa6d9a10-8d45-421b-8688-60bb7070079d)

**Comment by Ninjdai1** [comment]
I might have forgotten a count field in an output in the generation code, I'll look at it :)
Thanks for submitting this issue, it actually made me fix a lot of bugs !

**Comment by ZachsRoom** [comment]
Happy to help!
