### ISSUE TITLE
[Compat] Farmer's Respite

### ISSUE THREAD

**Issue by FemBane** [Ninjdai1/letsdo-addon-compat#11]
Farmer's Respite and Herbal Brews share tea brewing, also maybe Create Cafe? All 3 of these could honestly synergize REALLY well. I've been trying to write a compat primarily using KubeJS and ProbeJS for extracting what I can but... that's obviously not that successful

**Comment by FemBane** [comment]
[I am a special kind of stupid](https://www.curseforge.com/minecraft/mc-mods/lets-do-addon-fluids)

**Comment by VybeX** [comment]
i was wondering this as well, i see compat for herbal brews but not farmers respite.
