### ISSUE TITLE
Rats - cheese incompatibility

### ISSUE THREAD

**Issue by ElenaNya** [Ninjdai1/letsdo-addon-compat#2]
Minecraft 1.20.1
Forge 47.2.30
Letsdo-addon-compat-forge-v1.4.1
Rats-1.20.1-8.1.2
![image](https://github.com/Ninjdai1/letsdo-addon-compat/assets/94359925/e9788324-616b-4fd9-98cd-b3329c1513df)

**Comment by Ninjdai1** [comment]
What other mods are you running ? I specifically declare the tag you are showing with rats normal cheese aswell as meadow's :/

**Comment by ElenaNya** [comment]
> What other mods are you running ? I specifically declare the tag you are showing with rats normal cheese aswell as meadow's :/

![Screenshot_10](https://github.com/Ninjdai1/letsdo-addon-compat/assets/94359925/d81c9e07-85ba-498a-a767-486485a4a930)
![Screenshot_12](https://github.com/Ninjdai1/letsdo-addon-compat/assets/94359925/c2a9c0dd-4d9f-4c7b-b6fc-f4c926dbd059)
![Screenshot_13](https://github.com/Ninjdai1/letsdo-addon-compat/assets/94359925/561be2fd-2904-44b8-8b06-4383b52ce97e)

**Comment by ElenaNya** [comment]
Alright, that was much easier than I thought, literally just add rats:cheese in json

**Comment by BabblingFishes** [comment]
I'm having a problem that is probably related -- when this mod is installed, Rats will pick up and eat cheese thrown to them, but their WildTrust stat won't increase, so they can never be tamed.

I'm running about 150 mods, but I've been able to narrow it down to Let's Do Compat specifically. It's reproducible in a fresh instance of Minecraft 1.20.1 on Neoforge 47.1.105, with only the following mods:
- Architectury [9.2.14]
- Citadel [2.5.4]
- Rats [1.20.1-8.1.2]
- [Let's Do] API [1.2.11]
- [Let's Do Addon] Compat [1.4.1]

I suspect it's related to this error:
```
[17:02:02] [Worker-Main-2/ERROR] [minecraft/TagLoader]: Couldn't load tag forge:cheeses/nether as it is missing following references: 
	meadow:piece_of_warped_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
[17:02:02] [Worker-Main-2/ERROR] [minecraft/TagLoader]: Couldn't load tag forge:cheeses/normal as it is missing following references: 
	meadow:piece_of_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
	meadow:piece_of_sheep_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
	meadow:piece_of_grain_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
	meadow:piece_of_amethyst_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
	meadow:piece_of_buffalo_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
	meadow:piece_of_goat_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
[17:02:02] [Worker-Main-2/ERROR] [minecraft/TagLoader]: Couldn't load tag forge:cheeses as it is missing following references: 
	#forge:cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
	#forge:cheeses/normal (from Rats-1.20.1-8.1.2.jar)
	#forge:cheeses/nether (from Rats-1.20.1-8.1.2.jar)
```

I've attached latest.log and debug.log.
[latest.log](https://github.com/Ninjdai1/letsdo-addon-compat/files/15284303/latest.log)
[debug.log](https://github.com/Ninjdai1/letsdo-addon-compat/files/15284304/debug.log)

**Comment by Ninjdai1** [comment]
> I'm having a problem that is probably related -- when this mod is installed, Rats will pick up and eat cheese thrown to them, but their WildTrust stat won't increase, so they can never be tamed.
> 
> I'm running about 150 mods, but I've been able to narrow it down to Let's Do Compat specifically. It's reproducible in a fresh instance of Minecraft 1.20.1 on Neoforge 47.1.105, with only the following mods:
> 
>     * Architectury [9.2.14]
> 
>     * Citadel [2.5.4]
> 
>     * Rats [1.20.1-8.1.2]
> 
>     * [Let's Do] API [1.2.11]
> 
>     * [Let's Do Addon] Compat [1.4.1]
> 
> 
> I suspect it's related to this error:
> 
> ```
> [17:02:02] [Worker-Main-2/ERROR] [minecraft/TagLoader]: Couldn't load tag forge:cheeses/nether as it is missing following references: 
> 	meadow:piece_of_warped_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> [17:02:02] [Worker-Main-2/ERROR] [minecraft/TagLoader]: Couldn't load tag forge:cheeses/normal as it is missing following references: 
> 	meadow:piece_of_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> 	meadow:piece_of_sheep_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> 	meadow:piece_of_grain_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> 	meadow:piece_of_amethyst_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> 	meadow:piece_of_buffalo_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> 	meadow:piece_of_goat_cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> [17:02:02] [Worker-Main-2/ERROR] [minecraft/TagLoader]: Couldn't load tag forge:cheeses as it is missing following references: 
> 	#forge:cheese (from letsdo-addon-compat-forge-v1.4.1.jar)
> 	#forge:cheeses/normal (from Rats-1.20.1-8.1.2.jar)
> 	#forge:cheeses/nether (from Rats-1.20.1-8.1.2.jar)
> ```
> 
> I've attached latest.log and debug.log. [latest.log](https://github.com/Ninjdai1/letsdo-addon-compat/files/15284303/latest.log) [debug.log](https://github.com/Ninjdai1/letsdo-addon-compat/files/15284304/debug.log)

Fixed indev

**Comment by Ninjdai1** [comment]
I'll release the fix soon, this issue should be fixed indev.
If you were willing to try the development version  (https://github.com/Ninjdai1/letsdo-addon-compat/releases/tag/latest) to confirm this is indeed fixed, that would be very appreciated !
