### ISSUE TITLE
`farmersdelight:pot_cooking` is not a valid recipe type

### ISSUE THREAD

**Issue by unilock** [Ninjdai1/letsdo-addon-compat#5]
The `farmersdelight:pot_cooking` recipe type is referenced in over 400 files in this mod, according to GitHub.

However, such a recipe type does not exist. Did you mean `farmersdelight:cooking`?

That being said, it was a bit difficult to narrow down the log spam generated by this to this mod, as all of its recipes are placed in the namespaces of other mods (so the game reports broken recipes as belonging to other mods). Perhaps all the data could be relocated to a `letsdoaddon-compat` subfolder? This shouldn't affect functionality at all, unless the recipes are referenced by ID elsewhere.

**Comment by Ninjdai1** [comment]
That's a whoopsie, I don't know how I didn't notice that
Fixed indev

As for the ID, I'll move everything to subfolders to avoid the confusion

**Comment by unilock** [comment]
Awesome, thanks!
